### ISSUE TITLE
Documentation milestones.

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/evalai-cli#60]
# Write docs for.

- [x] Welcome page.
- [x] Installation.
- [x] Getting the token.
- [x] Connecting CLI to the host.
- [x] Basic commands overview.
- [x] View Challenge, Phase, Phase Splits. 
- [x] Create a participant team.
- [x] Participate in a challenge.
- [x] Make a submission.
- [x] View status of a submission.
- [x] View all your submission.
- [x] View the leaderboard.
- [x] Directory Structure.
- [x] Contributing guidelines.
- [x] Setting theme for the doc.

**Comment by isht3** [comment]
#59 #77 resolved this. Closing it now.[](url)
